# Generated by Django 4.0.2 on 2022-02-11 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Picture', models.CharField(max_length=100)),
                ('Content', models.CharField(max_length=50)),
                ('Date', models.DateTimeField()),
                ('Likes', models.IntegerField(default=0)),
                ('Dislikes', models.IntegerField(default=0)),
                ('Post_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Isadmin', models.BooleanField(default=False)),
                ('Isblocked', models.BooleanField(default=False)),
                ('Categories', models.ManyToManyField(to='djapp.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Postlike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Islike', models.BooleanField(default=False)),
                ('Isdislike', models.BooleanField(default=False)),
                ('Post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djapp.post')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='Tags',
            field=models.ManyToManyField(to='djapp.Tag'),
        ),
        migrations.AddField(
            model_name='post',
            name='User_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djapp.user'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.CharField(max_length=100)),
                ('Time', models.DateTimeField()),
                ('Post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djapp.post')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djapp.user')),
            ],
        ),
    ]
