# Generated by Django 4.0.2 on 2022-02-17 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0002_alter_comment_time_alter_post_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Picture',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
