# Generated by Django 4.0.2 on 2022-02-16 18:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('djapp', '0002_alter_comment_time_alter_post_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Likes',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
