# Generated by Django 4.0.2 on 2022-02-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0003_remove_post_likes_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='post',
            name='Likes',
            field=models.IntegerField(default=0),
        ),
    ]
