# Generated by Django 4.0.2 on 2022-02-17 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0006_post_likes_post_disliked_postlike_value1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='disliked',
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='value1',
        ),
    ]
