# Generated by Django 4.0.2 on 2022-02-17 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0003_alter_post_picture'),
        ('djapp', '0007_remove_post_disliked_remove_postlike_value1'),
    ]

    operations = [
    ]
