# Generated by Django 4.0.2 on 2022-02-21 04:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('djapp', '0008_merge_20220217_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='disliked',
            field=models.ManyToManyField(blank=True, default=None, related_name='disliked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postlike',
            name='value1',
            field=models.CharField(choices=[('Dislike', 'Dislike'), ('Cancel_Dislike', 'Cancel_Dislike')], default='Dislike', max_length=50),
        ),
    ]
